apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: call other org

on:
  workflow_dispatch:
    inputs:
        targetenv: 
            type: string
            default: targetenv

jobs:
  call:
    uses: gmaxey/subworkflows/.cloudbees/workflows/mlcbsimplerw.yaml
    vars: inherit
    secrets: inherit
    with:
        targetenv: ${{ inputs.targetenv }}