apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: inheritance tests
on:
  workflow_dispatch:
    inputs:
      targetenv:
        type: string
        default: ""
jobs:
  testcall:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable.yaml

  print:
    steps:
      - name: Print testvar in component
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar: ${{ vars.testvar }}"
      - name: Print testsec in component
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testsec: ${{ secrets.testsec }}"