apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: staged-workflow-sample

on:
  push:
    branches:
    - '**'
  workflow_dispatch:

metadata:
  stages/v1alpha1:
    - name: Stage 1
      jobs: [job-A, job-B]
    - name: Stage 2
      jobs: [job-C, job-D]


jobs:
  job-A:
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-A"
  job-B:
    needs: job-A
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-B"

#################### stage 2

  job-C:
    needs:
      - job-B
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-C"

  job-D:
    needs:
      - job-C
    steps:
    - uses: docker://alpine:3.20
      run: |
        echo "hello job-D"
