apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: override tests
on:
  workflow_dispatch:
    inputs:
      targetenv:
        type: string
      

jobs:
  
  # This one should work and print hardcode
   testoverride:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable3.yaml
    with:
      targetenv: ${{ inputs.targetenv }} 
    secrets:
      testsec: "hardcode"

  # This one should work and print hardcode
   testoverride_empty:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable3.yaml
    with:
      targetenv: "" 
    secrets:
      testsec: "hardcode"

  # This one should work and use print fromenv
   testoverride_hardcoded:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable3.yaml
    with:
      targetenv: "environment_mlcb_test_param"
    secrets:
      testsec: "hardcode"