apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Param environment in parallel exists nnnn
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      targetenv:
        type: string
        default: ''
jobs:
  testcall:
    uses: mluzcabrera/reusableworkflowsrepo/.cloudbees/workflows/reusable.yaml
    environment: testparamenv
    secrets: inherit
    vars: inherit
    with:
      targetenv: ${{ inputs.targetenv }}
