apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable
on:
  workflow_call:
    inputs:
      targetenv:
        type: string
        required: true

jobs:
  testparamenv:
    environment: environment_mlcb_test_param
    steps:
      - name: Print testvar
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar: ${{ vars.testvar }}"
      - name: Print testsec
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar: ${{ secrets.testsec }}"
